I'm pretty limited for this figure, because I drew most of it by hand in inkscape, which isn't always the best idea. Nevertheless, I can atleast go through the process of generating the data for that figure.

# Libraries

In [1]:
%load_ext rpy2.ipython

In [2]:
%%R 
library(tidyverse)
library(readxl)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.3.6      ✔ purrr   0.3.5
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1
✔ readr   2.1.3      ✔ forcats 0.5.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

# Data

In [3]:
%%R
best_hits <- read_csv("data/Ecoli_pangenome_best_hits.csv")

Rows: 7262 Columns: 25
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (8): qseqid, sseqid, component, cinful_id, pephash, sample, contig, seq
dbl (13): pident, length, mismatch, gapopen, qstart, qend, sstart, send, eva...
lgl  (4): hmmerHit, verified, allStandardAA, signalMatch

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [4]:
%%R
assemblySummary_ENAInformation <- read_excel("data/Ecoli_assemblySummary.xlsx", sheet="ENA-Information")

In [20]:
%%R -o assemblySummary_SequencedGenomes1
assemblySummary_SequencedGenomes1 <- read_excel("data/Ecoli_assemblySummary.xlsx", sheet="Sequenced-Genomes", skip=5) %>%
#	separate("Sequence_Name",c("phylogroup")) %>%
	select(c("Genome_ID","Isolation source","Strain Category")) %>%
	rename("GEMBASE_NAME"="Genome_ID") %>%
	drop_na()


assemblySummary_SequencedGenomes1

New names:
• `` -> `...8`
• `` -> `...20`
• `` -> `...28`
• `` -> `...35`
# A tibble: 1,304 × 3
   GEMBASE_NAME    `Isolation source` `Strain Category`
   <chr>           <chr>              <chr>
 1 ESCO.0216.00064 Host-associated    Mammal_Faecal
 2 ESCO.0216.00065 Environmental      Water
 3 ESCO.0216.00066 Host-associated    Human_Extra-intestinal
 4 ESCO.0216.00067 Host-associated    Human_Extra-intestinal
 5 ESCO.0216.00068 Host-associated    Mammal_Faecal
 6 ESCO.0216.00069 Host-associated    Human_Extra-intestinal
 7 ESCO.0216.00070 Environmental      Water
 8 ESCO.0216.00071 Environmental      Water
 9 ESCO.0216.00072 Host-associated    Human_Intestinal
10 ESCO.0216.00073 Host-associated    Human_Intestinal
# … with 1,294 more rows
# ℹ Use `print(n = ...)` to see more rows

In [21]:
%%R -o assemblySummary_SequencedGenomes
assemblySummary_SequencedGenomes <- read_excel("data/Ecoli_assemblySummary.xlsx", sheet="Australian-Dataset", skip=4) %>%
	select(c("Genome_ID","Phylogroup")) %>%
	rename("GEMBASE_NAME"="Genome_ID") %>%
	full_join(assemblySummary_SequencedGenomes1) %>%
	rename("phylogroup"="Phylogroup") %>%
	drop_na()


assemblySummary_SequencedGenomes

New names:
• `` -> `...4`
• `` -> `...13`
• `` -> `...14`
• `` -> `...22`
• `` -> `...32`
• `` -> `...37`
• `` -> `...38`
• `` -> `...39`
• `` -> `...40`
• `` -> `...41`
• `` -> `...42`
• `` -> `...50`
• `` -> `...57`
• `` -> `...65`
• `` -> `...71`
• `` -> `...74`
• `` -> `...75`
• `` -> `...76`
• `` -> `...80`
• `` -> `...83`
• `` -> `...84`
Joining, by = "GEMBASE_NAME"
# A tibble: 1,294 × 4
   GEMBASE_NAME    phylogroup `Isolation source` `Strain Category`
   <chr>           <chr>      <chr>              <chr>
 1 ESCO.0216.00064 A          Host-associated    Mammal_Faecal
 2 ESCO.0216.00065 B2         Environmental      Water
 3 ESCO.0216.00066 B2         Host-associated    Human_Extra-intestinal
 4 ESCO.0216.00067 B2         Host-associated    Human_Extra-intestinal
 5 ESCO.0216.00068 B2         Host-associated    Mammal_Faecal
 6 ESCO.0216.00069 B2         Host-associated    Human_Extra-intestinal
 7 ESCO.0216.00070 B2         Environmental      Water
 8 ESCO.0216.00071 B1         Environmental      Water
 9 ESCO.0216.00072 B2         Host-associated    Human_Intestinal
10 ESCO.0216.00073 D          Host-associated    Human_Intestinal
# … with 1,284 more rows
# ℹ Use `print(n = ...)` to see more rows

In [22]:
%%R -o assemblySummary_ENAInformation_phylogroup
assemblySummary_ENAInformation_phylogroup <- assemblySummary_ENAInformation %>% 
	full_join(assemblySummary_SequencedGenomes) %>%
	drop_na()

assemblySummary_ENAInformation_phylogroup

Joining, by = "GEMBASE_NAME"
# A tibble: 1,224 × 9
   GEMBASE_NAME  ASSEM…¹ ASSEM…² STUDY…³ SAMPL…⁴ CONTI…⁵ phylo…⁶ Isola…⁷ Strai…⁸
   <chr>         <chr>   <chr>   <chr>   <chr>   <chr>   <chr>   <chr>   <chr>
 1 ESCO.0216.00… M919    GCA_90… PRJEB3… ERS388… CADFUW… A       Host-a… Mammal…
 2 ESCO.0216.00… E5795   GCA_90… PRJEB3… ERS388… CADFUZ… B2      Enviro… Water
 3 ESCO.0216.00… H219    GCA_90… PRJEB3… ERS388… CADFVP… B2      Host-a… Human_…
 4 ESCO.0216.00… H144    GCA_90… PRJEB3… ERS388… CADFVR… B2      Host-a… Human_…
 5 ESCO.0216.00… E7727   GCA_90… PRJEB3… ERS388… CADFVL… B2      Enviro… Water
 6 ESCO.0216.00… E2508   GCA_90… PRJEB3… ERS388… CADFVH… B1      Enviro… Water
 7 ESCO.0216.00… 54_1_T… GCA_90… PRJEB3… ERS388… CADFVD… B2      Host-a… Human_…
 8 ESCO.0216.00… 47_4_R1 GCA_90… PRJEB3… ERS388… CADFVE… D       Host-a… Human_…
 9 ESCO.0216.00… M714    GCA_90… PRJEB3… ERS388… CADFVF… B2      Host-a… Mammal…
10 ESCO.0216.00… E7615   GCA_90… PRJEB3… ERS388… CADFVG… B2      Enviro… Water
# … with 1,214 more rows, and abbreviated variable names ¹​ASSEMBLY_NAME,
#   ²​ASSEMBLY_ACC, ³​STUDY_ID, ⁴​SAMPLE_ID, ⁵​CONTIG_ACC, ⁶​phylogroup,
#   ⁷​`Isolation source`, ⁸​`Strain Category`
# ℹ Use `print(n = ...)` to see more rows

In [23]:
%%R -o best_hits_assemblyID
best_hits_assemblyID <- best_hits %>%
	separate(cinful_id,c(NA, "ASSEMBLY_ACC_ID"), sep="/") %>%
	separate(ASSEMBLY_ACC_ID, c("ASSEMBLY_ACC"), sep = "[.]")

best_hits_assemblyID

# A tibble: 7,262 × 25
   qseqid         sseqid pident length misma…¹ gapopen qstart  qend sstart  send
   <chr>          <chr>   <dbl>  <dbl>   <dbl>   <dbl>  <dbl> <dbl>  <dbl> <dbl>
 1 v1_PLS_987b1c… E492_…   80.4     92      18       0      1    92      1    92
 2 v1_PLS_071967… L_tr_…   99.0    102       1       0      1   102      4   105
 3 v1_PLS_718e57… V_sp_…   81.2     16       3       0      1    16      1    16
 4 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 5 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 6 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 7 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 8 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 9 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
10 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
# … with 7,252 more rows, 15 more variables: evalue <dbl>, bitscore <dbl>,
#   component <chr>, hmmerHit <lgl>, verified <lgl>, ASSEMBLY_ACC <chr>,
#   pephash <chr>, sample <chr>, contig <chr>, start <dbl>, stop <dbl>,
#   strand <dbl>, allStandardAA <lgl>, seq <chr>, signalMatch <lgl>, and
#   abbreviated variable name ¹​mismatch
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names

In [24]:
%%R -o best_hits_phylogroup
best_hits_phylogroup <- best_hits_assemblyID %>%
	full_join(assemblySummary_ENAInformation_phylogroup) 

best_hits_phylogroup

Joining, by = "ASSEMBLY_ACC"
# A tibble: 7,262 × 33
   qseqid         sseqid pident length misma…¹ gapopen qstart  qend sstart  send
   <chr>          <chr>   <dbl>  <dbl>   <dbl>   <dbl>  <dbl> <dbl>  <dbl> <dbl>
 1 v1_PLS_987b1c… E492_…   80.4     92      18       0      1    92      1    92
 2 v1_PLS_071967… L_tr_…   99.0    102       1       0      1   102      4   105
 3 v1_PLS_718e57… V_sp_…   81.2     16       3       0      1    16      1    16
 4 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 5 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 6 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 7 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 8 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
 9 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
10 v1_PLS_f46b02… V_sp_…  100      103       0       0      1   103      1   103
# … with 7,252 more rows, 23 more variables: evalue <dbl>, bitscore <dbl>,
#   component <chr>, hmmerHit <lgl>, verified <lgl>, ASSEMBLY_ACC <chr>,
#   pephash <chr>, sample <chr>, contig <chr>, start <dbl>, stop <dbl>,
#   strand <dbl>, allStandardAA <lgl>, seq <chr>, signalMatch <lgl>,
#   GEMBASE_NAME <chr>, ASSEMBLY_NAME <chr>, STUDY_ID <chr>, SAMPLE_ID <chr>,
#   CONTIG_ACC <chr>, phylogroup <chr>, `Isolation source` <chr>,
#   `Strain Category` <chr>, and abbreviated variable name ¹​mismatch
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names

In [25]:
%%R -o microcin_hits_perPhylogroup
microcin_hits_perPhylogroup <- best_hits_phylogroup %>%
	filter(component == "microcins.verified") %>%
    filter(hmmerHit == "TRUE") %>%
	group_by(sseqid, phylogroup) %>%
	summarise(n = n())
microcin_hits_perPhylogroup

`summarise()` has grouped output by 'sseqid'. You can override using the
`.groups` argument.
# A tibble: 42 × 3
# Groups:   sseqid [8]
   sseqid                     phylogroup     n
   <chr>                      <chr>      <int>
 1 E492_sp_Q9Z4N4_MCEA_KLEPN  F              1
 2 H47_sp_P62530_MCHB_ECOLX   A              1
 3 H47_sp_P62530_MCHB_ECOLX   B1             5
 4 H47_sp_P62530_MCHB_ECOLX   B2            23
 5 H47_sp_P62530_MCHB_ECOLX   C              1
 6 H47_sp_P62530_MCHB_ECOLX   D              5
 7 H47_sp_P62530_MCHB_ECOLX   F              1
 8 H47_sp_P62530_MCHB_ECOLX   G              3
 9 I47_tr_Q712Q0_Q712Q0_ECOLX A              2
10 I47_tr_Q712Q0_Q712Q0_ECOLX B1             5
# … with 32 more rows
# ℹ Use `print(n = ...)` to see more rows

In [26]:
microcin_hits_perPhylogroup

                        sseqid phylogroup   n
1    E492_sp_Q9Z4N4_MCEA_KLEPN          F   1
2     H47_sp_P62530_MCHB_ECOLX          A   1
3     H47_sp_P62530_MCHB_ECOLX         B1   5
4     H47_sp_P62530_MCHB_ECOLX         B2  23
5     H47_sp_P62530_MCHB_ECOLX          C   1
6     H47_sp_P62530_MCHB_ECOLX          D   5
7     H47_sp_P62530_MCHB_ECOLX          F   1
8     H47_sp_P62530_MCHB_ECOLX          G   3
9   I47_tr_Q712Q0_Q712Q0_ECOLX          A   2
10  I47_tr_Q712Q0_Q712Q0_ECOLX         B1   5
11  I47_tr_Q712Q0_Q712Q0_ECOLX         B2   5
12  I47_tr_Q712Q0_Q712Q0_ECOLX          C   1
13  I47_tr_Q712Q0_Q712Q0_ECOLX          D   6
14  I47_tr_Q712Q0_Q712Q0_ECOLX          F   1
15  I47_tr_Q712Q0_Q712Q0_ECOLX          G   3
16    L_tr_Q841V4_Q841V4_ECOLX          A   2
17    L_tr_Q841V4_Q841V4_ECOLX         B1   1
18    L_tr_Q841V4_Q841V4_ECOLX         B2   3
19    L_tr_Q841V4_Q841V4_ECOLX          D   1
20    M_tr_Q83TS1_Q83TS1_ECOLX          A   1
21    M_tr_Q83TS1_Q83TS1_ECOLX         B1   6
22    M_tr_Q83TS1_Q83TS1_ECOLX         B2  39
23    M_tr_Q83TS1_Q83TS1_ECOLX          D   5
24    M_tr_Q83TS1_Q83TS1_ECOLX          E   1
25    M_tr_Q83TS1_Q83TS1_ECOLX          F   2
26    M_tr_Q83TS1_Q83TS1_ECOLX          G   3
27  PDI_tr_I6ZU90_I6ZU90_ECOLX          A   4
28  PDI_tr_I6ZU90_I6ZU90_ECOLX         B1   6
29  PDI_tr_I6ZU90_I6ZU90_ECOLX         B2   4
30  PDI_tr_I6ZU90_I6ZU90_ECOLX          C   3
31  PDI_tr_I6ZU90_I6ZU90_ECOLX          D   6
32  PDI_tr_I6ZU90_I6ZU90_ECOLX          F   2
33    S_tr_H9ZMG7_H9ZMG7_ECOLX         B1   1
34    S_tr_H9ZMG7_H9ZMG7_ECOLX          D   1
35      V_sp_P22522_CEAV_ECOLX          A  36
36      V_sp_P22522_CEAV_ECOLX         B1  37
37      V_sp_P22522_CEAV_ECOLX         B2  85
38      V_sp_P22522_CEAV_ECOLX          C  10
39      V_sp_P22522_CEAV_ECOLX          D   9
40      V_sp_P22522_CEAV_ECOLX          E   5
41      V_sp_P22522_CEAV_ECOLX          F  12
42      V_sp_P22522_CEAV_ECOLX          G  17

In [11]:
%%R 
microcin_hits_perPhylogroup #%>%
#	pivot_wider(values_from=n, names_from=phylogroup)

# A tibble: 42 × 3
# Groups:   sseqid [8]
   sseqid                     phylogroup     n
   <chr>                      <chr>      <int>
 1 E492_sp_Q9Z4N4_MCEA_KLEPN  F              1
 2 H47_sp_P62530_MCHB_ECOLX   A              1
 3 H47_sp_P62530_MCHB_ECOLX   B1             5
 4 H47_sp_P62530_MCHB_ECOLX   B2            23
 5 H47_sp_P62530_MCHB_ECOLX   C              1
 6 H47_sp_P62530_MCHB_ECOLX   D              5
 7 H47_sp_P62530_MCHB_ECOLX   F              1
 8 H47_sp_P62530_MCHB_ECOLX   H299           3
 9 I47_tr_Q712Q0_Q712Q0_ECOLX A              2
10 I47_tr_Q712Q0_Q712Q0_ECOLX B1             5
# … with 32 more rows
# ℹ Use `print(n = ...)` to see more rows

So that's where the data comes from. I just took the known phylogenetic relationships of the verified micrcoins, as well as the known relationships between the phylogroups and hand drew dendrograms such that each axis is phylogenetically sorted. Then the boxes were colored by the number, and left blank f NA

Now we can do a little statistical assesment of how the phylogroups aren't equally represented in this analysis

In [ ]:
%%R
n_assembliesPhylogroup <- assemblySummary_ENAInformation_phylogroup %>%
	count(phylogroup, name="n_assemblies") %>%
	mutate(freq_assemblies = n_assemblies / sum(n_assemblies))
n_assembliesPhylogroup

In [ ]:
%%R
best_hits_phylogroup_expected <- best_hits_phylogroup %>%
	filter(component == "microcins.verified") %>%
	group_by(phylogroup) %>%
	summarise(n_microcins = n()) %>%
	full_join(n_assembliesPhylogroup) %>%
	mutate(expected_microcins = sum(n_microcins) * freq_assemblies)
best_hits_phylogroup_expected

In [ ]:
%%R
chisq.test(x = best_hits_phylogroup_expected$n_assemblies)

In [ ]:
%%R
chisq.test(x = best_hits_phylogroup_expected$n_microcins, p = best_hits_phylogroup_expected$freq_assemblies)